[package]
name = "comembert"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.26"
dirs = "5.0"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
serde_json = "1.0"
fzf-wrapped = "0.1"
clap = { version = "4.5.20", features = ["derive"] }
sysinfo = "0.32"
